[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:dotnet]
command=dotnet OpenShort.Api.dll
directory=/app
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/dotnet.err.log
stdout_logfile=/var/log/supervisor/dotnet.out.log
environment=ASPNETCORE_URLS="http://*:8080"

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/nginx.err.log
stdout_logfile=/var/log/supervisor/nginx.out.log
